import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Breaking Bad Quotes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div className="flex h-[calc(100vh-5rem)] bg-zinc-800">
          <Suspense fallback="loading"> {children}</Suspense>
        </div>
      </body>
    </html>
  );
}
